### PR TITLE
configure.ac: Check mpicc better at --with-mpich

### PR DESCRIPTION
**Pull request by gc00**
* If mpicc not present, ./configure lead to extraneous printouts

### CODE REVIEW

**Comment by JainTwinkle** [comment]
@gc00 It looks like Travis is hanged. Could you check that?
LGTM otherwise.

**Comment by gc00** [comment]
Bugs in Travis.  The tests succeeded, but Travis won't report status to github.  Will close and re-open to try to annoy Travis into working again.

**Comment by gc00** [comment]
close and re-open again to satisfy buggy travis/github.

**Comment by gc00** [comment]
[Re-sending.  A bug in Microsoft Outlook refused to let me simply reply.  I had to reply to this new message.]

Hi Twinkle,
    Travis/Github seems to be full of bugs.  For example, see this recent issue:
  https://travis-ci.community/t/travis-ci-build-status-doesnt-show-up-anymore-in-pull-requests/8718
[ as of June, 2020 ]

The Travis UI showed that the PR had passed the Travis tests, but Travis wouldn't tell Github that.

I tried setting some random things in the Travis settings.  After that, Github removed the Travis checks, and it's not obvious how to get them back.

But I think you can now review the PR.

Also, I gave you admin privileges for DMTCP.  Whichever of us has free time first can try to investigate further what Github/Travis wants from us.  Apparently they changed their system in Octobaer, 2019.

Best,
- Gene

________________________________________

**Pull request merged**
