### PR TITLE
Fix random restart bug; seen in MVAPICH @ Stampede

### PR DESCRIPTION
**Pull request by gc00**
Proposal to solve bug in issue #56

### CODE REVIEW

**Comment by karya0** [comment]
Closing now since issue #56 has already been solved by a4d67bf. If you are still seeing the bug, please feel free to reopen the issue and this PR?

 If you see the bug, could you do a sanity check and provide me the steps to reproduce it?

**Comment by karya0** [comment]
I didn't realize that you had already reopened #56.

**Comment by gc00** [comment]
Just reminding everyone why this pull request still exists.  A version of the random restart bug was observed on Stampede with MVAPICH.  That bug is not fixed bya4d67bf3e5db0b7933390f58547ffc500a37f640 from @karya0.  The pull request here (re-enable mtcp_check_vdso() does fix it.  @karya0 said he would like to analyze the bug more deeply to see if there is a more targeted bug fix.  @rohgarg and @jiajuncao have both observed the current random restart bug on Stampede, in case @karya0 wants to discuss the details of what was observed.

**Comment by karya0** [comment]
Merged via e6ec0e6c74e1878693338176e7cc7e1c6b5c65f4.

**Comment by gc00** [comment]
@karya0: Apparently, you closed this as part of the 2.4.0-rc3 tag.
But don't we want to re-open it now, since this fix is not included
in the master branch?

**Comment by karya0** [comment]
The patch has been merged in master. Let's create a separate issue and keep this PR closed.

**Pull request closed without merging**
