### PR TITLE
fileconnlist: Mark /proc/pid/environ as pre-existing fd

### PR DESCRIPTION
**Pull request by rohgarg**
This fixes issue #439.

### CODE REVIEW

**Comment by rohgarg** [comment]
@angel-smile: Could you please test this patch (again)? This is a cleaned up version of what I had provided to you earlier.

@subhasisb: Could you please review this? This workaround is required for supporting PBS.

**Comment by subhasisb** [comment]
@rohgarg the change itself looks good. One question though: Besides PBS, if any application happens to have a legitimate fd to /proc/<pid>/environ, how would checkpointing such an application be effected by this change?

**Comment by rohgarg** [comment]
@subhasisb: Since the case only triggers when the `PBS_JOBID` env. var. is set, other applications should not be affected by this change. Also, if an application explicitly opens a fd to `/proc/<pid>/environ` during its runtime, the fd will go through the regular checkpoint-restart logic. This change only affects an application that's launched under PBS (with the `PBS_JOBID` env. var set) and that inherits the `/proc/<pid/environ` fd from its PBS launcher parent process.

**Comment by subhasisb** [comment]
Ah yes, of course, you have the check for PBS_JOBID. So that covers it. A follow up question though. What is it a actual problem for dmtcp to checkpoint if the application launched under PBS inherits an fd? I mean, what we are doing here is fine code wise, but sounds like a workaround, no?

**Comment by angel-smile** [comment]
@rohgarg Many thanks for it! I've tested with a bioinformatics application that it works for me under PBS with DMTCP v2.5 and v3.0.0.

**Comment by gc00** [comment]
@subhasisb , The function `FileConnList::scanForPreExisting()` is intended to check for any file descriptors that were in existence prior to an application starting,  Typically, this happens because a monitor process opened a file descriptor and then forked and exec'ed into the actual application.  If DMTCP is checkpointing only the application and not the monitor process, then DMTCP has no way of knowing how to restore the fd of the monitor process during restart.  So, we punt, and we don't try to restore any pre-existing fd's.

@rohgarg, I'm approving this PR.  But I wonder if we should have an issue about better documenting all of these special cases of pre-existing fd's.  Or in general, we should document what we whiltelist and blacklist.  Do we already have an issue that covers that?

**Comment by subhasisb** [comment]
Thanks for the explanation @gc00  - I understand now.

**Pull request merged**
