### PR TITLE
documentation: differentiate between ^C and kill

### PR DESCRIPTION
**Pull request by rohgarg**

### CODE REVIEW

**Comment by gc00** [comment]
A userr (on dmtcp-forum?) had used ^C instead of 'dmtcp_command -k' to kill a job with more than one process.  I believe the story is that some of the processes continued to live, and so the DMTCP coordinator did not exit.  After that, connecting to the default DMTCP coordinator did not work as expected.  We need to document that ^C is not as reliable as `dmtcp_command --kill`.

**Comment by gc00** [comment]
@karya0 and @rohgarg, I was the one who asked to make this a pull request, rather than an issue.  I think it's very important for us to support less experienced users who are confused by things like this.

In my view, this is an example of issue #109.  Hence, I propose to write code in the DMTCP coordinator that will notify inexperienced users when they accidentally launch a new process that silently joins the coordinator.

I propose to write the fairly trivial code to solve this.  But I'd like to get my code reviewed before I write it.  :-)

**PROPOSED CODE FOR REVIEW:**  Suppose that dmtcp_coordinator is already running with one process.  I propose that if a new request comes to the coordinator via a second `dmtcp_launch` (not via `fork()` or exec()`), then we will print a second header.  We will respect the `--quiet` flag for users who don't like this.  Note that when using MPI, it can happen for some resource manager, that many separate processes call `dmtcp_launch` separately.  But in these cases, the HPC environment should already be siphoning off the output of dmtcp_coordinator or using `--quiet`.  So, the proposed new functionality should not interfere with MPI situation.

Can I get a pre-review before I write this code?  Thanks.

**Comment by gc00** [comment]
@karya0 and I talked.  We'll do a more ambitious change.  The user must type ``--join`` in order to join an existing computation.  If there is no current computation, ``--join`` will fail.  If the user typed ``--join``, then we don't need to re-print the launch header.  This will also fix the problem of a user joining an existing computation without realizing it.  I'll change this pull request later.

**Comment by karya0** [comment]
Let's merge it.

**Comment by karya0** [comment]
Merged.

**Pull request closed without merging**
