### PR TITLE
Add git-bisect.sh to util

### PR DESCRIPTION
**Pull request by gc00**
This creates a file that, with slight modifications, can be used for the git bisect command:
   `git bisect run git-bisect.sh`
At the beginning of the file, git-bisect.sh has comments on how to use this file.

### CODE REVIEW

**Comment by karya0** [comment]
@gc00: Looks like your branch isn't in sync with dmtcp/dmtcp:master. Could you fix that and update the PR?

**Comment by gc00** [comment]
It's now in sync again, and the pull request is updated.

**Comment by gc00** [comment]
I've now updated the template for git-bisect.sh to also include git-bisect-m32.sh.  In both cases, the template now starts the search from tag 2.0, tests against dmtcp1 only, and assumes that "good" means everything passes, and "bad" means that we got at least as far as autotest.py, which printed "ckpt:".  Any other result is considered a "skip" for "git bisect.

**Comment by karya0** [comment]
Merged via 15c312e36d843823c0072573658a522e3722d490.

**Pull request closed without merging**
