### PR TITLE
Disabled vfork tests in autotest.py.

### PR DESCRIPTION
**Pull request by karya0**
Minor update to .gitignore file.

### CODE REVIEW

**Comment by JainTwinkle** [comment]
Could you provide some reasoning behind disabling tests?

**Comment by karya0** [comment]
Vfork support and tests are broken currently and we intend to fix it later
when we have someone using vfork.

**Comment by JainTwinkle** [comment]
Do we have any existing Github issue or bug to reference to show what exactly is broken? If not, then could you please create one? We can label it as TODO to ensure that we address the issue in the future.

**Comment by karya0** [comment]
> Do we have any existing Github issue or bug to reference to show what exactly is broken? If not, then could you please create one? We can label it as TODO to ensure that we address the issue in the future.

I created https://github.com/dmtcp/dmtcp/issues/983. Since we don't have a precedence for tracking github issues in code, I'll skip the TODO for now.

**Review by JainTwinkle — APPROVED** [review]
Thanks for creating #983; approving this one.

**Pull request merged**
