### PR TITLE
Issue in checkpointing opened file deleted in between by parent 

### PR DESCRIPTION
**Pull request by ankitcse07**
Consider a scenario in which file is already opened by
parent and now child process is forked. DMTCP infrastructure
doesn't populates _flags field in FileConnection class of
child process. Now at certain time file is deleted using
unlink however file pointer was not closed. Further
child process invokes the application level checkpoint.

This has resulted in issue. Fix is to use _fcntlFlags
filed

### CODE REVIEW

**Comment by ankitcse07** [comment]
Please see the attached test, reproducing the issue 

[PR394_test.tar.gz](https://github.com/dmtcp/dmtcp/files/289401/PR394_test.tar.gz)

**Comment by rohgarg** [comment]
LGTM.

**Comment by ankitcse07** [comment]
@rohgarg 3.0.0 milestone means this is also required to be committed to master branch right ?

**Comment by ankitcse07** [comment]
d0dbba6 commit done in 2.5 branch

**Comment by ankitcse07** [comment]
I am closing this PR and will raise new PR for checking in into master branch

**Pull request closed without merging**
