### PR TITLE
fileconnection: add check to verify the existence of a dir

### PR DESCRIPTION
**Pull request by rohgarg**
This patch is a workaround for what is arguably a bug in the Luster
FS. See: https://jira.hpdd.intel.com/browse/LU-6528.  When multiple
independent processes call mkdir() on an existing directory,
a process can sometimes get an EACCES error, which causes our
createDirectoryStructure function to assert. This patch adds an
extra check (using the stat() call) in createDirectoryStructure in
case the call to mkdir() returned EACCES.

### CODE REVIEW

**Comment by gc00** [comment]
@rohgarg: Does this replace pull request #120, or is it in addiont?

**Comment by rohgarg** [comment]
Sorry I forgot to mention, this replaces pull request #120.

**Comment by rohgarg** [comment]
@gc00, @karya0: Ping. :-)

**Comment by karya0** [comment]
LGTM.

**Pull request merged**
