### PR TITLE
Slurm FT plugin

### PR DESCRIPTION
**Pull request by rohgarg**

### CODE REVIEW

**Comment by gc00** [comment]
Nice submission.  (As before, issue #321 is the reason for travis failing.)  I'd like to propose changing the plugin name to `slurm-ckpt-on-kill` or some or some other more meaningful name.  I'd like to get the right balance between short and meaningful.  Suggestions, anyone?

**Comment by rohgarg** [comment]
@gc00: Sure, I don't have a strong opinion either way. I have now also tested the plugin with SLURM, and it seems to work okay. I'll add a sample batch script in the test subdirectory.

**Comment by gc00** [comment]
Then if you like the change in the name for the plugin, then it looks good to me.

**Comment by MikeDacre** [comment]
I am trying to run this myself, but I am getting the error:

    ERROR: ld.so: object '/home/dacre/dmtcp/dmtcp-2.4.4/contrib/slurm-ft/slurm-ft.o' from LD_PRELOAD cannot be preloaded: ignored.

My submission script is here: https://gist.github.com/MikeDacre/c2875bcff4ccae8771a3

**Comment by gc00** [comment]
@rohgarg, could you update the PR to resolve conflicts and then take a look at the comment of @MikeDacre .  This PR seems to have been orphaned, and we should bring it back to life.  Thanks.

**Comment by gc00** [comment]
@rohgarg, I have the same comment as @MikeDacre:  This PR seems to have been orphaned, and we should bring it back to life. Thanks.

**Comment by rohgarg** [comment]
@MikeDacre: I looked at your submission script. The `--with-plugin` takes in a path to the *.so file. Could you please re-try after changing your command to:
  `srun dmtcp_launch --with-plugin /path/to/libdmtcp_slurm-ft.so --checkpoint-open-files python test.py`?

(Your script was referring to the *.o file instead of the *.so file.)

**Pull request merged**
