### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by alexmyczko**
drop unuploaded changelog entry, close bug, fix version

### CODE REVIEW

**Comment by alexmyczko** [comment]
I also tried to modernize debian/rules, here's my complete package (with tests disabled, more arches in, tried sparc64/kfreebsd-amd64 (they fail))

http://phd-sid.ethz.ch/debian/dmtcp/26/

**Comment by yarikoptic** [comment]
@alexmyczko I have not looked into your changes yet but FYI: modernization of `debian/*` should be done with backports in mind since dmtcp is also destined for a wide range of backports to be provided from neurodebian, see http://neuro.debian.net/pkgs/dmtcp.html .  So debhelper compat should be no greater than 10 ATM to get most of the recent debian/ubuntu releases covered

**Comment by alexmyczko** [comment]
it should be 12 for sid and 10 for all backports then. can give it a try tomorrow

**Comment by yarikoptic** [comment]
Sid version of debhelper still supports 10 afaik

**Pull request merged**
