### PR TITLE
ib-plugin: Fix compilation error introduced in f2d2a7

### PR DESCRIPTION
**Pull request by rohgarg**

### CODE REVIEW

**Comment by karya0** [comment]
The correct fix is to change `bool` to `int` in dmtcp.h for the following line:
```   bool __dmtcp_plugin_ckpt_disabled = dmtcp_plugin_disable_ckpt()
```

This way we still keep dmtcp.h favorable for .c files.

**Comment by rohgarg** [comment]
Updated the PR.

**Comment by karya0** [comment]
Let's commit it (after squashing the two commits).

**Comment by rohgarg** [comment]
Closed via 229add881d22b5bbc372c260483352fbc5925dbd.

**Pull request closed without merging**
