### PR TITLE
change dmtcp version to 2.5.1

### PR DESCRIPTION
**Pull request by shlomiya**
Required in order to create an up-to-date Fedora package

### CODE REVIEW

**Comment by rohgarg** [comment]
@shlomiya Isn't this for the 2.5 branch?

**Comment by rohgarg** [comment]
@gc00 But shouldn't the target branch for the PR be 2.5? It's currently targeted for the master branch.

**Comment by gc00** [comment]
Ahh!  At least, the PR should especially be targeted to 2.5.  Adding it to 3.0/master
is harmless.

Good point!  I'll re-open the PR.
- Gene

----- Original Message -----

**Comment by gc00** [comment]
@shlomiya, Do you have any response to @rohgarg?  He notes that this PR is targeted against 3.0/master with a patch to change the version nmber to 2.5.

**Pull request closed without merging**
