### PR TITLE
Fix restart case where all root procs are orphaned.

### PR DESCRIPTION
**Pull request by artpol84**
@gc00 @ankitcse07 
Ankit, this fixes your case. Please, verify.

### CODE REVIEW

**Comment by artpol84** [comment]
I'm getting the following warning:
```
[41000] WARNING at terminal.cpp:110 in restore_term_settings; REASON='JWARNING(false) failed'
Message: :skip restore terminal step -- we are in BACKGROUND
```
It clearly gets the case correctly, I'll let you to decide wether to keep it or remove or refine the conditions.

**Comment by ankitcse07** [comment]
Thanks @artpol84 , I will get back to you if this covers all my cases.

**Comment by artpol84** [comment]
@ankitcse07 @gc00 @karya0 
Can this be merged (after update)?

**Comment by ankitcse07** [comment]
@artpol84 Thanks for the fix, this is working fine now. Please go ahead and merge, let me know when this can be available in  master branch.  For the time being, I will merge this locally

**Comment by artpol84** [comment]
@karya0 Can you check if this is something not-related to this commit?
I just rebased it against the latest master.

**Comment by gc00** [comment]
@artpol84, your code is correct.  It failed because of issue #321 concerning an earlier commit.  I've asked @karya0 to take a look at the issue with the earlier commit.

By the way, the code looks good to me.  When @karya0 fixes the earlier commit, you'll be able to rebase.  Then Travis will accept your commit, and you can push it in.  When you do that, could you push in both for the branch 2.5 and for master (which will be branch 3.0)?  Thanks.

**Comment by artpol84** [comment]
Sure, thanks!

четверг, 25 февраля 2016 г. пользователь Gene Cooperman написал:

> @artpol84 <https://github.com/artpol84>, your code is correct. It failed
> because of issue #321 <https://github.com/dmtcp/dmtcp/issues/321>
> concerning an earlier commit. I've asked @karya0
> <https://github.com/karya0> to take a look at the issue with the earlier
> commit.
>
> By the way, the code looks good to me. When @karya0
> <https://github.com/karya0> fixes the earlier commit, you'll be able to
> rebase. Then Travis will accept your commit, and you can push it in. When
> you do that, could you push in both for the branch 2.5 and for master
> (which will be branch 3.0)? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmtcp/dmtcp/pull/300#issuecomment-188878596>.
>


-- 
-----
Best regards, Artem Polyakov
(Mobile mail)

**Comment by gc00** [comment]
четверг, 3 март 2016 г. пользователь Gene Cooperman написал:
@artpol84, the issue with Travis has been fixed now.  Could you push this in now?  Please push it in to _both_ the master branch and the 2.5 branch.  Спасибо.

**Pull request merged**
