### PR TITLE
Comment JLOG call, fails with --enable-debug

### PR DESCRIPTION
**Pull request by FrancoisAi**
The title makes it clear.

### CODE REVIEW

**Comment by rohgarg** [comment]
Thanks for the patch, @FrancoisAi. There's an existing issue for tracking this. See issue #332. IIRC, @karya0 had a patch for this that works without having to comment out the call to `JLOG`. @karya0, would you be able to push that in?

**Comment by gc00** [comment]
@karya0, Ping.  :-)  Should we directly push in this pull request ourselves, or do you have a preferred solution based on issue #332?

**Comment by rohgarg** [comment]
Ship it!

**Comment by rohgarg** [comment]
This PR was migrated to #460 and pushed in.

**Pull request closed without merging**
