### PR TITLE
Updated NEWS and bumped revision to 2.4.8

### PR DESCRIPTION
**Pull request by gc00**
The title speaks for itself.  We should push this in after any pending PR's for 2.4.8.

### CODE REVIEW

**Comment by rohgarg** [comment]
I think we'll have one more set of fixes and so the NEWS file will need to be updated. In particular, I'm working on porting PR #557 (fixes for epoll) to the 2.4 branch.

**Comment by rohgarg** [comment]
I have now pushed in the changes for PR #557 to the 2.5 and 2.4 branches. I think the only thing we are missing now for the 2.4.8 release is a fix for issue #538.

**Comment by gc00** [comment]
@rohgarg, Please seem my comment at issue #538 here:  https://github.com/dmtcp/dmtcp/issues/538#issuecomment-279260227
Let me know what you think of this plan.

**Comment by gc00** [comment]
@rohgarg, Since you've now added the missing fix, is this ready to be pushed in?

**Comment by rohgarg** [comment]
Sure, but do you also need to run `autogen.sh` to generate the updated configure script (with the new version information)?

**Comment by gc00** [comment]
Good point.  I've added a commit to run autogen.sh with the new VERSION.  Next, I'll push it in.

**Pull request merged**
